apiVersion: apps/v1
kind: Deployment
metadata:
  name: goserver
  labels:
    app: goserver
spec:
  selector:
    matchLabels:
      app: goserver    
  replicas: 5
  template:
    metadata:
      labels:
        app: "goserver"
    spec:
      containers:
        - name: goserver
          image: "amandasdn/hello-amanda:latest"

          resources:
            requests: 
              cpu: "0.05"
              memory: 20Mi
            limits:
              cpu: "0.05"
              memory: 25Mi
              
          startupProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 4
            failureThreshold: 30

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 3
            failureThreshold: 1
            initialDelaySeconds: 10
            
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            periodSeconds: 5
            failureThreshold: 1
            timeoutSeconds: 1
            successThreshold: 1
            initialDelaySeconds: 15

          envFrom:
            - configMapRef:
                name: configmap-env
            - secretRef:
                name: goserver-secret

          volumeMounts:
            - mountPath: "/go/family"
              name: config

      volumes:

        - name: config
          configMap:
            name: configmap-pets
            items:
            - key: members
              path: "pets.txt" 

